### ISSUE TITLE
1.19.1

### ISSUE THREAD

**Issue by NakyoykaN** [kkllffaa/meteor-litematica-printer#12]
Litematica is updated to 1.19.1

Can this get bumped up?  

The 1.19 version crashes when I try to load it anyways.

**Comment by NakyoykaN** [comment]
+Bump 1.19.2 is out.

Crashes when this is loaded.

**Comment by Wide-Cat** [comment]
resolved as of 2a287f45e0ebb0159852b990d1a175955c5dcb14
